### ISSUE TITLE
EmailListItem and powershell variable

### ISSUE THREAD

**Issue by javadbacker** [EvotecIT/Emailimo#2]
Just wanted to highlight to you that variable value is not getting read in EmailListItem -text

```
EmailList -FontSize 15 {
				EmailListItem -Text 'Client comments pending on three engineering documents.'  
				EmailListItem -Text 'Vessel setup reports for marine scope is ongoing. '  
				EmailListItem -Text 'Current Productivity is **$productivity**'  
			}
```

_The value of $productivity is not being read_
OUTPUT is as below

•	Client comments pending on three engineering documents.
•	Vessel setup reports for marine scope is ongoing. 
•	Current Productivity is $productivity

The variable values in below line are working well.
`EmailText -Text "		Estimated Man-hours at Award =	$($manhourBudgetSummary_Array[0])"`

**Comment by PrzemyslawKlys** [comment]
Well you're using single quotes. Change it to double quotes and it will work? 

```powershell
EmailList -FontSize 15 {
				EmailListItem -Text 'Client comments pending on three engineering documents.'  
				EmailListItem -Text 'Vessel setup reports for marine scope is ongoing. '  
				EmailListItem -Text "Current Productivity is **$productivity**"
}
```

**Comment by javadbacker** [comment]
Yeah, it is working well. Thanks

**Comment by javadbacker** [comment]
I tried to use **backtick - Line breaks** in strings to have multi-lines. But this is not working. 
No line breaks in output at the backtick `n

```
$activitiesNextWeek_String = $activitiesNextWeek_String  + "activity one" + " `n"
$activitiesNextWeek_String = $activitiesNextWeek_String  + "activity two" + " `n"
$activitiesNextWeek_String = $activitiesNextWeek_String  + "activity three"

EmailTextBox {
				$activitiesNextWeek_String 
			}
```

**Comment by PrzemyslawKlys** [comment]
There are 2 ways to achieve what you want. 

1. Use EmailTextBox with an array

```powershell
EmailTextbox {
     "Line one"
     "Line two"
     "Line three"
     "" #empty line
}
```

So this can be done in a way

```powershell
$Text = @(
     "Line one"
     "Line two"
     "Line three"
     "" #empty line
)
EmailTextBox {
     $Text
}
```

2. Use EmailText with -LineBreak switch

```powershell
EmailText -Text '...','...' -LineBreak 
```

You should review this: https://evotec.xyz/meet-emailimo-new-way-to-send-pretty-emails-with-powershell/

**Comment by javadbacker** [comment]
Used ArrayList and working great. Thanks again. 

```
EmailTextBox {
				$forecastActivitiesForNextWeek_ArrayList
			}
```

**Comment by javadbacker** [comment]
System.Data.DataTable in Email has extra columns. 

As I understood from https://docs.microsoft.com/en-us/dotnet/api/system.data.datarow.rowstate?view=netframework-4.8
These are row properties 

![image](https://user-images.githubusercontent.com/19654105/60388030-ca4bb880-9abc-11e9-8c2a-96d988baf7d0.png)

Snapshot from Powershell for the table output

`$cseProgress_dataTable`
![image](https://user-images.githubusercontent.com/19654105/60387878-f23a1c80-9aba-11e9-8d1f-f330667c70c7.png)

Snapshot from email for the below code 

```
EmailText -LineBreak
EmailTable -Table $cseProgress_dataTable -HideFooter -DisableInfo 
EmailText -LineBreak
```

![image](https://user-images.githubusercontent.com/19654105/60387897-1eee3400-9abb-11e9-8142-54a42369bd0c.png)

**Comment by PrzemyslawKlys** [comment]
I don't think there's much one can do with this except for rewriting it to a more PS object. I can probably add some feature that will help you do it automatically at some point but try this

```powershell
$NewObject = $cseProgress_dataTable | Select-Object -Property ProgressSummary, PlannedProgress,EarnedProgress,ExpendedManHours

EmailTable -DataTable $NewObject -HideFooter
```
Alternatively

```powershell
EmailTable -DataTable ($cseProgress_dataTable | Select-Object -Property ProgressSummary, PlannedProgress,EarnedProgress,ExpendedManHours) -HideFooter

**Comment by javadbacker** [comment]
Rewrote to PS object and works. 

`$New_cseProgress_dataTable = $cseProgress_dataTable | Select-Object -Property ProgressSummary, PlannedProgress,EarnedProgress,ExpendedManHours`

```
EmailText -Text 'C.	CSE Progress Summary' -TextDecoration underline -FontWeight bold
			EmailText -LineBreak
			EmailTable -Table $New_cseProgress_dataTable -HideFooter   # -DisableInfo -DisablePaging -DisableProcessing
			EmailText -LineBreak
			EmailTable -Table $cseProgress_dataTable -HideFooter   
```

![image](https://user-images.githubusercontent.com/19654105/60388765-04ba5300-9ac7-11e9-8d2a-8319cd204832.png)

_snapshot from email_

**Comment by PrzemyslawKlys** [comment]
You can also rewrite it in a bit more controlled way. Prettier way. 

````powershell
$New_cseProgress_dataTable = foreach ($_ in $cseProgress_dataTable) {
    [PSCustomObject]@{
        'Progress Summary' = $_.ProgressSummary
        'Planned Progress' = $_.PlannedProgress
        # and so on
    }
}
```

The rewriting is pretty fast so no real slowdown and you control how your table looks like.

**Comment by javadbacker** [comment]
Hi

Email sending error 

```
Email -Supress $false  {
....
	Write-Log -Message "SENDING EMAIL with email_IMO" -Path "$WeeklyProgressReportsFolder\Script.log" -Level Info 
	Write-Log -Message "test.Status $($test.Status)"  -Path "$WeeklyProgressReportsFolder\Script.log" -Level Info 
	Write-Log -Message "test.SentTo $($test.SentTo)"  -Path "$WeeklyProgressReportsFolder\Script.log" -Level Info 
	Write-Log -Message "test.Error  $($test.Error)"   -Path "$WeeklyProgressReportsFolder\Script.log" -Level Info 

}
```

Output as below 

```
VERBOSE: SENDING EMAIL with email_IMO
VERBOSE: test.Status False
VERBOSE: test.SentTo 
VERBOSE: test.Error  Exception calling "Send" with "1" argument(s): "Failure sending mail."
```

I also tried below connection test

`Test-NetConnection -Port 587 -ComputerName smtp.office365.com -InformationLevel Detailed`

Output

```
WARNING: TCP connect to (40.100.28.210 : 587) failed
WARNING: TCP connect to (40.100.29.210 : 587) failed
WARNING: TCP connect to (40.100.29.226 : 587) failed
WARNING: TCP connect to (52.98.65.2 : 587) failed
WARNING: Ping to 40.100.28.210 failed with status: TimedOut
WARNING: Ping to 40.100.29.210 failed with status: TimedOut
WARNING: Ping to 40.100.29.226 failed with status: TimedOut
WARNING: Ping to 52.98.65.2 failed with status: TimedOut


ComputerName            : smtp.office365.com
RemoteAddress           : 40.100.28.210
RemotePort              : 587
NameResolutionResults   : 40.100.28.210
                          40.100.29.210
                          40.100.29.226
                          52.98.65.2
MatchingIPsecRules      : 
NetworkIsolationContext : Internet
IsAdmin                 : False
InterfaceAlias          : Ethernet 3
SourceAddress           : 10.161.39.15
NetRoute (NextHop)      : 10.161.39.1
PingSucceeded           : False
PingReplyDetails (RTT)  : 0 ms
TcpTestSucceeded        : False
```

**Comment by PrzemyslawKlys** [comment]
I guess you checked the -Ssl switch and port -587 for EmailServer?

**Comment by javadbacker** [comment]
Yes. The port default value is 587.  Therefore I didn't change that. 
-ssl switch is on

I had this problem during one evening. Thought it was due to long PowerShell session between computer standby etc. Shutdown computer and then it started working. Now i tried the same. Not working as of now.

I can also see that the emailimo uses send-email instead of Send-MailMessage.
Don't know if this is some issue with the server smtp.office365.com.

**Comment by PrzemyslawKlys** [comment]
Yes I'm using my own Send-Email function instead of Send-Mailmessage due to lack of some things in Send-MailMessage. 

Is it possible you're firewall blocked? Test-NetConnection shows you can't connect so that would mean your machine is cut off from 587 port.

**Comment by javadbacker** [comment]
Yes, maybe. But it worked for me ten or 15 times while testing earlier. 

```
$email = "mYmail@gmail.com" 
$pass = "myPassWord" 
$smtpServer = "smtp.gmail.com" 
  
$msg = new-object Net.Mail.MailMessage 
$smtp = new-object Net.Mail.SmtpClient($smtpServer) 
$smtp.EnableSsl = $true 
$msg.From = "$email"  
$msg.To.Add("$email") 
$msg.BodyEncoding = [system.Text.Encoding]::Unicode 
$msg.SubjectEncoding = [system.Text.Encoding]::Unicode 
$msg.IsBodyHTML = $true  
$msg.Subject = "Test mail from PS" 
$msg.Body = "<h2> Test mail from PS </h2> 
</br> 
Hi there 
"  
$SMTP.Credentials = New-Object System.Net.NetworkCredential("$email", "$pass"); 
$smtp.Send($msg)
```

I'm having a similar error with the above code as well. 

```
Exception calling "Send" with "1" argument(s): "Failure sending mail."
At line:22 char:1
+ $smtp.Send($msg)
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SmtpException
```

**Comment by javadbacker** [comment]
:( Looks like it. 
Is there a way for me to access the saved HTML so that I can use it in the email body of the below script.

```
function compose-OutlookEmail 
{

	$outlookFolderDrafts = 16
	$outlookObject = New-Object -comObject Outlook.Application 
	$nameSpace = $outlookObject.GetNameSpace("MAPI")

	# call the save method yo dave the email in the drafts folder
	$mail = $outlookObject.CreateItem(0)
	$null = $Mail.Recipients.Add("XXX@YYY.ZZZ")  
	$Mail.Subject = $email_Subject 
	# $Mail.Body = "  Test Mail  "
	$Mail.HTMLBody = " **This is an HTML Email Body** "
	$mail.Attachments.Add($Source);
	$Mail.importance = 2 
	$Mail.save()

	# get it back from drafts and update the body
	$drafts = $nameSpace.GetDefaultFolder($outlookFolderDrafts)
	$draft = $drafts.Items | where {$_.subject -eq $email_Subject}
	$draft.body += "`n foo bar"
	$draft.save()

}
compose-OutlookEmail 
```

**Comment by PrzemyslawKlys** [comment]
Yes. 

```powershell
Email -FilePath $File -WhatIf {

}
```

This will create HTML but will not send an email. I actually do development that way. So I use FilePath and keep HTML file open in a browser and just press F5 to refresh content to see how things changed.

**Comment by javadbacker** [comment]
Thanks. Yes. I got the HTML file as a body in draft email.

[string]$htmlFile_AsString = Get-Content $htmlFile

function compose-OutlookEmail 
{

	$outlookFolderDrafts = 16
	$outlookObject = New-Object -comObject Outlook.Application 
	$nameSpace = $outlookObject.GetNameSpace("MAPI")

	# call the save method yo dave the email in the drafts folder
	$mail = $outlookObject.CreateItem(0)
	$null = $Mail.Recipients.Add("XXX@YYY.ZZZ")  
	$Mail.Subject = $email_Subject 
	$Mail.HTMLBody = "$htmlFile_AsString"
	$Mail.importance = 2 # 2 = High importance message
	$Mail.save()

	# get it back from drafts and update the body
	$drafts = $nameSpace.GetDefaultFolder($outlookFolderDrafts)
	$draft = $drafts.Items | where {$_.subject -eq $email_Subject}
	$draft.body += "`n foo bar"
	$draft.save()

}
compose-OutlookEmail

**Comment by javadbacker** [comment]
Emailimo has been working well for me. Thanks a lot.

When I am using the below code, the size of the font that results in outlook is 10 and not 13 

`EmailBody -FontFamily "Arial Nova" **-Size 13** {
            EmailText -Text "All, $currentTime"  # , $UserNotify, "," -Color None, Blue, None -Verbose -LineBreak
            EmailText -LineBreak
            EmailText -Text "Please see below the progress on CSE deliverables for the D6978 NFPS I1P1 project. Detailed document status is attached."
            EmailText -LineBreak
            EmailText -Text 'A.	Activities done during current week' -TextDecoration underline -FontWeight bold
            EmailText -LineBreak
}`

**Comment by javadbacker** [comment]
Also, the color shading of the title row in EmailTable has changed recently from deep blue to back. Is this the case?

**_old shading color_**
![image](https://user-images.githubusercontent.com/19654105/62928721-2303b600-bdca-11e9-87be-bfab78365ffc.png)


**_new color shading_**

![image](https://user-images.githubusercontent.com/19654105/62928601-e2a43800-bdc9-11e9-9ffa-10ba240af547.png)

**Comment by PrzemyslawKlys** [comment]
You can change the color of titles so that's not really a problem. Have you tried changing it?

**Comment by javadbacker** [comment]
No because i haven't really tried changing the title of the table as i'm always installing emailImo like below

```
Install-Module Emailimo -Force -Scope CurrentUser
Import-Module PSWriteHTML -Force
Import-Module Emailimo -Force
```

I'm not able to find the file 'EmailTable.ps1' in your repository path as well. 
 Emailimo/Public/Features,

**Comment by PrzemyslawKlys** [comment]
You should read:
- https://evotec.xyz/working-with-html-in-powershell-just-got-better/
- https://evotec.xyz/all-your-html-tables-are-belong-to-us/

Both will tell you how you can influence EmailHeader or EmailContent. 

The thing is EmailTable is an alias of New-HTMLTable so you can use EmailTable just like you would use New-HTMLTable (which is described in articles). 

Same goes for New-HTMLTableHeader which has an alias of EmailTableHeader and you can do the same thing as described in artlces. 

```powershell
        EmailTable -DataTable $DomainControllers {
            EmailTableHeader -Names 'IPV4Address', 'IPV6Address' -Title 'Ip Addresses' -Alignment center -Color White -BackGroundColor Gray
            EmailTableHeader -Names 'SchemaMaster', 'PDCEmulator', 'RIDMaster', 'DomainNamingMasterMaster', 'InfrastructureMaster' -Title 'Roles' -Alignment center -Color White -BackGroundColor Gray
            EmailTableHeader -Names 'LdapPort', 'SslPort' -Title 'Ports' -Alignment center -Color White -BackGroundColor Gray
            EmailTableCondition -ComparisonType 'string' -Name 'SchemaMaster' -Operator eq -Value 'True' -BackgroundColor Green -Color White -Inline
            EmailTableCondition -ComparisonType 'string' -Name 'PDCEmulator' -Operator eq -Value 'True' -BackgroundColor Green -Color White -Inline
            EmailTableCondition -ComparisonType 'string' -Name 'RIDMaster' -Operator eq -Value 'True' -BackgroundColor Green -Color White -Inline
            EmailTableCondition -ComparisonType 'string' -Name 'IsReadOnly' -Operator eq -Value 'True' -BackgroundColor Yellow -Color Black -Inline
            EmailTableCondition -ComparisonType 'string' -Name 'Pingable' -Operator eq -Value 'True' -BackgroundColor Green -Color White -Inline
            EmailTableCondition -ComparisonType 'string' -Name 'Pingable' -Operator ne -Value 'True' -BackgroundColor Red -Color White -Inline
        } -HideFooter
```

You can pretty much influence how headers or content is styled with colors or apply conditions on the fly.

**Comment by javadbacker** [comment]
👍👍

**Comment by javadbacker** [comment]
**Font size in outlook** 

When I am using the below code, the size of the **font that results in outlook is 10 and not 13**

EmailBody -FontFamily "Arial Nova" -Size 13 {
            EmailText -Text "All, $currentTime"  # , $UserNotify, "," -Color None, Blue, None -Verbose -LineBreak
            EmailText -LineBreak
            EmailText -Text "Please see below the progress on Engg. deliverables for the D6000 NFRE I2P4 project. Detailed document status is attached."
            EmailText -LineBreak
            EmailText -Text 'A.	Activities done during current week' -TextDecoration underline -FontWeight bold
            EmailText -LineBreak
}

**Comment by PrzemyslawKlys** [comment]
I believe it's an issue with Outlook:
- https://stackoverflow.com/questions/8078572/email-html-font-size-in-outlook

**Comment by javadbacker** [comment]
Oh ok thanks 👍
