### ISSUE TITLE
Cant send email on anonymous internal server

### ISSUE THREAD

**Issue by lkitsos** [EvotecIT/Emailimo#4]
Try it with ip and host name but no luck

EmailServer -Server 'x.x.x.x'

I can verify that i can send mail with send-mailmessage.

Thank you

**Comment by michalzobec** [comment]
I have same problem.

**Comment by PrzemyslawKlys** [comment]
```
$Test = Email -Supress $False {
...
}
$Test.Status
$Test.Error
$Test.SentTo
```

Use Suppress $false to get results and see what the return is. You may want to use -Port because most likely you require 25 rather than default 587. You may also need to play with SSL parameter.

**Comment by lkitsos** [comment]
You are correct need to add port 25.

Thank you for your help.
